import { axiosSgAPI } from '@/connections/axios-init';
import { apiStepSequenceType } from '@/types/step-sequence-type';

export function getStepSequence() {
  return { data: response };
  return axiosSgAPI.get<apiStepSequenceType[]>('/step-sequence-generator');
}

const response = [
  {
    id: 'ID141',
    name: 'вальсовый шаг с правой',
    transitionDirection: 'forward',
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 'right',
    endLeg: 'left',
    isChangeLeg: true,
    startEdge: 'outer',
    endEdge: 'outer',
    isChangeEdge: false,
    isSpeedIncrease: true,
    isDifficult: false,
    type: 'sequence',
    description: '',
    absoluteName: 'unknown',
    distance: 3,
    coordinates: {
      vector: 'east',
      start: {
        x: 30,
        y: 25,
      },
      end: {
        x: 39,
        y: 25,
      },
    },
  },
  {
    id: 'ID112',
    name: 'выкрюк назад наружу на левой',
    transitionDirection: 'backward',
    rotationDirection: 1,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'left',
    isChangeLeg: false,
    startEdge: 'outer',
    endEdge: 'outer',
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'counter',
    distance: 2,
    coordinates: {
      vector: 'east',
      start: {
        x: 39,
        y: 25,
      },
      end: {
        x: 45,
        y: 25,
      },
    },
  },
  {
    id: 'ID102',
    name: 'крюк вперед наружу на левой',
    transitionDirection: 'forward',
    rotationDirection: 1,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'left',
    isChangeLeg: false,
    startEdge: 'outer',
    endEdge: 'outer',
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'rocker',
    distance: 2,
    coordinates: {
      vector: 'south',
      start: {
        x: 45,
        y: 25,
      },
      end: {
        x: 45,
        y: 19,
      },
    },
  },
  {
    id: 'ID66',
    name: 'подпрыжка назад на правой на левую с полуповоротом вправо',
    transitionDirection: 'backward',
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'left',
    isChangeLeg: false,
    startEdge: 'outer',
    endEdge: 'inner',
    isChangeEdge: true,
    isSpeedIncrease: true,
    isDifficult: false,
    type: 'hop',
    description: '',
    absoluteName: 'unknown',
    distance: 1,
    coordinates: {
      vector: 'east',
      start: {
        x: 45,
        y: 19,
      },
      end: {
        x: 48,
        y: 19,
      },
    },
  },
  {
    id: 'ID127',
    name: 'твизл вперед внутрь на левой',
    transitionDirection: 'forward',
    rotationDirection: 2,
    rotationDegree: 1080,
    startLeg: 'left',
    endLeg: 'left',
    isChangeLeg: false,
    startEdge: 'inner',
    endEdge: 'inner',
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'twizzle',
    distance: 3,
    coordinates: {
      vector: 'south_east',
      start: {
        x: 48,
        y: 19,
      },
      end: {
        x: 57,
        y: 10,
      },
    },
  },
  {
    id: 'ID95',
    name: 'тройка вперед внутрь на левой',
    transitionDirection: 'forward',
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'left',
    isChangeLeg: false,
    startEdge: 'inner',
    endEdge: 'outer',
    isChangeEdge: true,
    isSpeedIncrease: false,
    isDifficult: false,
    type: 'turn',
    description: '',
    absoluteName: 'unknown',
    distance: 1,
    coordinates: {
      vector: 'south',
      start: {
        x: 57,
        y: 10,
      },
      end: {
        x: 57,
        y: 7,
      },
    },
  },
  {
    id: 'ID112',
    name: 'выкрюк назад наружу на левой',
    transitionDirection: 'backward',
    rotationDirection: 1,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'left',
    isChangeLeg: false,
    startEdge: 'outer',
    endEdge: 'outer',
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'counter',
    distance: 2,
    coordinates: {
      vector: 'south',
      start: {
        x: 57,
        y: 7,
      },
      end: {
        x: 57,
        y: 1,
      },
    },
  },
];
