import { sgInstance } from '@/api/sequence-generator/instance-sg-api';
import { SequenceLevelType } from '@/types/sg-api/request-types';
import { GetStepSequenceType, Movement } from '@/types/sg-api/response-types';
import { DistanceFactorType } from '@/types/distance-factor.type';

const movements = [
  {
    id: 'ID6',
    name: 'кроссролл назад с левой',
    transitionDirection: 'backward',
    rotationDirection: 0,
    rotationDegree: 0,
    startLeg: 'left',
    endLeg: 'right',
    isChangeLeg: true,
    startEdge: 'outer',
    endEdge: 'outer',
    isChangeEdge: false,
    isSpeedIncrease: true,
    isDifficult: false,
    type: 'unknown',
    description: '',
    absoluteName: 'unknown',
    distance: 1,
    coordinates: {
      vector: 'south_east',
      start: {
        x: 30,
        y: 5,
      },
      end: {
        x: 33,
        y: 2,
      },
    },
  },
  {
    id: 'ID108',
    name: 'выкрюк назад наружу на правой',
    transitionDirection: 'backward',
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 'right',
    endLeg: 'right',
    isChangeLeg: false,
    startEdge: 'outer',
    endEdge: 'outer',
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'counter',
    distance: 2,
    coordinates: {
      vector: 'east',
      start: {
        x: 33,
        y: 2,
      },
      end: {
        x: 39,
        y: 2,
      },
    },
  },
  {
    id: 'ID21',
    name: 'козлик с правой',
    transitionDirection: 'forward',
    rotationDirection: 0,
    rotationDegree: 0,
    startLeg: 'right',
    endLeg: 'right',
    isChangeLeg: false,
    startEdge: 'twoEdges',
    endEdge: 'twoEdges',
    isChangeEdge: false,
    isSpeedIncrease: true,
    isDifficult: false,
    type: 'hop',
    description: '',
    absoluteName: 'unknown',
    distance: 1,
    coordinates: {
      vector: 'north_east',
      start: {
        x: 39,
        y: 2,
      },
      end: {
        x: 42,
        y: 5,
      },
    },
  },
  {
    id: 'ID91',
    name: 'тройка вперед внутрь на правой',
    transitionDirection: 'forward',
    rotationDirection: 1,
    rotationDegree: 180,
    startLeg: 'right',
    endLeg: 'right',
    isChangeLeg: false,
    startEdge: 'inner',
    endEdge: 'outer',
    isChangeEdge: true,
    isSpeedIncrease: false,
    isDifficult: false,
    type: 'turn',
    description: '',
    absoluteName: 'unknown',
    distance: 1,
    coordinates: {
      vector: 'north_west',
      start: {
        x: 42,
        y: 5,
      },
      end: {
        x: 39,
        y: 8,
      },
    },
  },
  {
    id: 'ID52',
    name: 'ласточка назад наружу на левой',
    transitionDirection: 'backward',
    rotationDirection: 0,
    rotationDegree: 0,
    startLeg: 'right',
    endLeg: 'left',
    isChangeLeg: true,
    startEdge: 'twoEdges',
    endEdge: 'outer',
    isChangeEdge: true,
    isSpeedIncrease: false,
    isDifficult: false,
    type: 'glide',
    description: 'ласточка или ее вариации',
    absoluteName: 'unknown',
    distance: 3,
    coordinates: {
      vector: 'north_west',
      start: {
        x: 39,
        y: 8,
      },
      end: {
        x: 30,
        y: 17,
      },
    },
  },
  {
    id: 'ID96',
    name: 'тройка назад наружу на левой',
    transitionDirection: 'backward',
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'left',
    isChangeLeg: false,
    startEdge: 'outer',
    endEdge: 'inner',
    isChangeEdge: true,
    isSpeedIncrease: false,
    isDifficult: false,
    type: 'turn',
    description: '',
    absoluteName: 'unknown',
    distance: 1,
    coordinates: {
      vector: 'south_west',
      start: {
        x: 30,
        y: 17,
      },
      end: {
        x: 27,
        y: 14,
      },
    },
  },
  {
    id: 'ID103',
    name: 'крюк вперед внутрь на левой',
    transitionDirection: 'forward',
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'left',
    isChangeLeg: false,
    startEdge: 'inner',
    endEdge: 'inner',
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'rocker',
    distance: 2,
    coordinates: {
      vector: 'north_west',
      start: {
        x: 27,
        y: 14,
      },
      end: {
        x: 21,
        y: 20,
      },
    },
  },
  {
    id: 'ID105',
    name: 'крюк назад внутрь на левой',
    transitionDirection: 'backward',
    rotationDirection: 1,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'left',
    isChangeLeg: false,
    startEdge: 'inner',
    endEdge: 'inner',
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'rocker',
    distance: 2,
    coordinates: {
      vector: 'south_west',
      start: {
        x: 21,
        y: 20,
      },
      end: {
        x: 15,
        y: 14,
      },
    },
  },
  {
    id: 'ID79',
    name: 'моухок вперёд внутрь на левой',
    transitionDirection: 'forward',
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'right',
    isChangeLeg: true,
    startEdge: 'inner',
    endEdge: 'inner',
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: false,
    type: 'step',
    description: '',
    absoluteName: 'unknown',
    distance: 1,
    coordinates: {
      vector: 'north_west',
      start: {
        x: 15,
        y: 14,
      },
      end: {
        x: 12,
        y: 17,
      },
    },
  },
  {
    id: 'ID101',
    name: 'крюк назад внутрь на правой',
    transitionDirection: 'backward',
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 'right',
    endLeg: 'right',
    isChangeLeg: false,
    startEdge: 'inner',
    endEdge: 'inner',
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'rocker',
    distance: 2,
    coordinates: {
      vector: 'north',
      start: {
        x: 12,
        y: 17,
      },
      end: {
        x: 12,
        y: 23,
      },
    },
  },
  {
    id: 'ID134',
    name: 'чиктао вперёд внутрь с правой',
    transitionDirection: 'forward',
    rotationDirection: 1,
    rotationDegree: 180,
    startLeg: 'right',
    endLeg: 'left',
    isChangeLeg: true,
    startEdge: 'inner',
    endEdge: 'outer',
    isChangeEdge: true,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'step',
    description: '',
    absoluteName: 'chocktaw',
    distance: 2,
    coordinates: {
      vector: 'north_east',
      start: {
        x: 12,
        y: 23,
      },
      end: {
        x: 18,
        y: 29,
      },
    },
  },
  {
    id: 'ID139',
    name: 'чиктао назад наружу с левой',
    transitionDirection: 'backward',
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 'left',
    endLeg: 'right',
    isChangeLeg: true,
    startEdge: 'outer',
    endEdge: 'inner',
    isChangeEdge: true,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'step',
    description: '',
    absoluteName: 'chocktaw',
    distance: 2,
    coordinates: {
      vector: 'south_east',
      start: {
        x: 18,
        y: 29,
      },
      end: {
        x: 24,
        y: 23,
      },
    },
  },
] as unknown as Movement[];

export const sgApi = {
  getStepSequence(
    sequenceLevel: SequenceLevelType = 1,
    distanceFactor: DistanceFactorType = 3
  ) {
    return { data: movements };

    return sgInstance.get<GetStepSequenceType>(`/sg-step`, {
      params: {
        sequenceLevel: sequenceLevel,
        distanceFactor: distanceFactor,
      },
    });
  },
  test() {
    return movements;
  },
};
