import { sgInstance } from '@/api/sequence-generator/instance-sg-api';
import { SequenceLevelType } from '@/types/sg-api/request-types';
import { GetStepSequenceType, Movement } from '@/types/sg-api/response-types';
import { DistanceFactorType } from '@/types/distance-factor.type';

const movements = [
  {
    id: 'ID110',
    name: 'выкрюк вперед наружу на левой',
    transitionDirection: 1,
    rotationDirection: 2,
    rotationDegree: 180,
    startLeg: 0,
    endLeg: 0,
    isChangeLeg: false,
    startEdge: 1,
    endEdge: 1,
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'counter',
    distance: 2,
    coordinates: {
      vector: 'north_east',
      start: {
        x: 6,
        y: 36,
      },
      end: {
        x: 8,
        y: 38,
      },
    },
  },
  {
    id: 'ID128',
    name: 'твизл назад наружу на левой',
    transitionDirection: 2,
    rotationDirection: 2,
    rotationDegree: 1080,
    startLeg: 0,
    endLeg: 0,
    isChangeLeg: false,
    startEdge: 1,
    endEdge: 1,
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'twizzle',
    distance: 3,
    coordinates: {
      vector: 'south_east',
      start: {
        x: 8,
        y: 38,
      },
      end: {
        x: 11,
        y: 35,
      },
    },
  },
  {
    id: 'ID129',
    name: 'твизл назад внутрь на левой',
    transitionDirection: 2,
    rotationDirection: 1,
    rotationDegree: 1080,
    startLeg: 0,
    endLeg: 0,
    isChangeLeg: false,
    startEdge: 0,
    endEdge: 0,
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'twizzle',
    distance: 3,
    coordinates: {
      vector: 'south',
      start: {
        x: 11,
        y: 35,
      },
      end: {
        x: 11,
        y: 32,
      },
    },
  },
  {
    id: 'ID67',
    name: 'подпрыжка назад на правой на левую с полуповоротом влево',
    transitionDirection: 2,
    rotationDirection: 1,
    rotationDegree: 180,
    startLeg: 0,
    endLeg: 0,
    isChangeLeg: false,
    startEdge: 0,
    endEdge: 1,
    isChangeEdge: true,
    isSpeedIncrease: true,
    isDifficult: false,
    type: 'hop',
    description: '',
    absoluteName: 'unknown',
    distance: 1,
    coordinates: {
      vector: 'east',
      start: {
        x: 11,
        y: 32,
      },
      end: {
        x: 12,
        y: 32,
      },
    },
  },
  {
    id: 'ID102',
    name: 'крюк вперед наружу на левой',
    transitionDirection: 1,
    rotationDirection: 1,
    rotationDegree: 180,
    startLeg: 0,
    endLeg: 0,
    isChangeLeg: false,
    startEdge: 1,
    endEdge: 1,
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'rocker',
    distance: 2,
    coordinates: {
      vector: 'south_east',
      start: {
        x: 12,
        y: 32,
      },
      end: {
        x: 14,
        y: 30,
      },
    },
  },
  {
    id: 'ID120',
    name: 'петля назад наружу на левой',
    transitionDirection: 2,
    rotationDirection: 2,
    rotationDegree: 360,
    startLeg: 0,
    endLeg: 0,
    isChangeLeg: false,
    startEdge: 1,
    endEdge: 1,
    isChangeEdge: false,
    isSpeedIncrease: false,
    isDifficult: true,
    type: 'turn',
    description: '',
    absoluteName: 'loop',
    distance: 1,
    coordinates: {
      vector: 'east',
      start: {
        x: 14,
        y: 30,
      },
      end: {
        x: 15,
        y: 30,
      },
    },
  },
] as Movement[];

export const sgApi = {
  getStepSequence(
    sequenceLevel: SequenceLevelType = 1,
    distanceFactor: DistanceFactorType = 3
  ) {
    // return sgInstance.get<GetStepSequenceType>(`/sg-step`, {
    //   params: {
    //     sequenceLevel: sequenceLevel,
    //     distanceFactor: distanceFactor,
    //   },
    // });
    return {
      data: [
        {
          id: 'ID110',
          name: 'выкрюк вперед наружу на левой',
          transitionDirection: 1,
          rotationDirection: 2,
          rotationDegree: 180,
          startLeg: 0,
          endLeg: 0,
          isChangeLeg: false,
          startEdge: 1,
          endEdge: 1,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'counter',
          distance: 2,
          coordinates: {
            vector: 'south_west',
            start: {
              x: 17,
              y: 17,
            },
            end: {
              x: 11,
              y: 11,
            },
          },
        },
        {
          id: 'ID100',
          name: 'крюк назад наружу на правой',
          transitionDirection: 2,
          rotationDirection: 1,
          rotationDegree: 180,
          startLeg: 1,
          endLeg: 1,
          isChangeLeg: false,
          startEdge: 1,
          endEdge: 1,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'rocker',
          distance: 2,
          coordinates: {
            vector: 'west',
            start: {
              x: 11,
              y: 11,
            },
            end: {
              x: 5,
              y: 11,
            },
          },
        },
        {
          id: 'ID104',
          name: 'крюк назад наружу на левой',
          transitionDirection: 2,
          rotationDirection: 2,
          rotationDegree: 180,
          startLeg: 0,
          endLeg: 0,
          isChangeLeg: false,
          startEdge: 1,
          endEdge: 1,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'rocker',
          distance: 2,
          coordinates: {
            vector: 'north',
            start: {
              x: 5,
              y: 11,
            },
            end: {
              x: 5,
              y: 17,
            },
          },
        },
        {
          id: 'ID140',
          name: 'вальсовый шаг с левой',
          transitionDirection: 1,
          rotationDirection: 1,
          rotationDegree: 180,
          startLeg: 0,
          endLeg: 1,
          isChangeLeg: true,
          startEdge: 1,
          endEdge: 1,
          isChangeEdge: false,
          isSpeedIncrease: true,
          isDifficult: false,
          type: 'sequence',
          description: '',
          absoluteName: 'unknown',
          distance: 3,
          coordinates: {
            vector: 'east',
            start: {
              x: 5,
              y: 17,
            },
            end: {
              x: 14,
              y: 17,
            },
          },
        },
        {
          id: 'ID92',
          name: 'тройка назад наружу на правой',
          transitionDirection: 2,
          rotationDirection: 1,
          rotationDegree: 180,
          startLeg: 1,
          endLeg: 1,
          isChangeLeg: false,
          startEdge: 1,
          endEdge: 0,
          isChangeEdge: true,
          isSpeedIncrease: false,
          isDifficult: false,
          type: 'turn',
          description: '',
          absoluteName: 'unknown',
          distance: 1,
          coordinates: {
            vector: 'north_east',
            start: {
              x: 14,
              y: 17,
            },
            end: {
              x: 17,
              y: 20,
            },
          },
        },
        {
          id: 'ID56',
          name: 'простая подпрыжка вперёд на левой на правую',
          transitionDirection: 1,
          rotationDirection: 0,
          rotationDegree: 0,
          startLeg: 1,
          endLeg: 1,
          isChangeLeg: false,
          startEdge: 2,
          endEdge: 2,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: false,
          type: 'hop',
          description: '',
          absoluteName: 'unknown',
          distance: 1,
          coordinates: {
            vector: 'north_west',
            start: {
              x: 17,
              y: 20,
            },
            end: {
              x: 14,
              y: 23,
            },
          },
        },
        {
          id: 'ID21',
          name: 'козлик с правой',
          transitionDirection: 1,
          rotationDirection: 0,
          rotationDegree: 0,
          startLeg: 1,
          endLeg: 1,
          isChangeLeg: false,
          startEdge: 2,
          endEdge: 2,
          isChangeEdge: false,
          isSpeedIncrease: true,
          isDifficult: false,
          type: 'hop',
          description: '',
          absoluteName: 'unknown',
          distance: 1,
          coordinates: {
            vector: 'north',
            start: {
              x: 14,
              y: 23,
            },
            end: {
              x: 14,
              y: 26,
            },
          },
        },
        {
          id: 'ID107',
          name: 'выкрюк вперед внутрь на правой',
          transitionDirection: 1,
          rotationDirection: 2,
          rotationDegree: 180,
          startLeg: 1,
          endLeg: 1,
          isChangeLeg: false,
          startEdge: 0,
          endEdge: 0,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'counter',
          distance: 2,
          coordinates: {
            vector: 'east',
            start: {
              x: 14,
              y: 26,
            },
            end: {
              x: 20,
              y: 26,
            },
          },
        },
        {
          id: 'ID110',
          name: 'выкрюк вперед наружу на левой',
          transitionDirection: 1,
          rotationDirection: 2,
          rotationDegree: 180,
          startLeg: 0,
          endLeg: 0,
          isChangeLeg: false,
          startEdge: 1,
          endEdge: 1,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'counter',
          distance: 2,
          coordinates: {
            vector: 'south_west',
            start: {
              x: 17,
              y: 17,
            },
            end: {
              x: 11,
              y: 11,
            },
          },
        },
        {
          id: 'ID100',
          name: 'крюк назад наружу на правой',
          transitionDirection: 2,
          rotationDirection: 1,
          rotationDegree: 180,
          startLeg: 1,
          endLeg: 1,
          isChangeLeg: false,
          startEdge: 1,
          endEdge: 1,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'rocker',
          distance: 2,
          coordinates: {
            vector: 'west',
            start: {
              x: 11,
              y: 11,
            },
            end: {
              x: 5,
              y: 11,
            },
          },
        },
        {
          id: 'ID104',
          name: 'крюк назад наружу на левой',
          transitionDirection: 2,
          rotationDirection: 2,
          rotationDegree: 180,
          startLeg: 0,
          endLeg: 0,
          isChangeLeg: false,
          startEdge: 1,
          endEdge: 1,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'rocker',
          distance: 2,
          coordinates: {
            vector: 'north',
            start: {
              x: 5,
              y: 11,
            },
            end: {
              x: 5,
              y: 17,
            },
          },
        },
        {
          id: 'ID116',
          name: 'петля назад наружу на правой',
          transitionDirection: 2,
          rotationDirection: 1,
          rotationDegree: 360,
          startLeg: 1,
          endLeg: 1,
          isChangeLeg: false,
          startEdge: 1,
          endEdge: 1,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'loop',
          distance: 1,
          coordinates: {
            vector: 'north',
            start: {
              x: 20,
              y: 26,
            },
            end: {
              x: 20,
              y: 29,
            },
          },
        },
        {
          id: 'ID111',
          name: 'выкрюк вперед внутрь на левой',
          transitionDirection: 1,
          rotationDirection: 1,
          rotationDegree: 180,
          startLeg: 0,
          endLeg: 0,
          isChangeLeg: false,
          startEdge: 0,
          endEdge: 0,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'counter',
          distance: 2,
          coordinates: {
            vector: 'north_east',
            start: {
              x: 20,
              y: 29,
            },
            end: {
              x: 26,
              y: 35,
            },
          },
        },
        {
          id: 'ID120',
          name: 'петля назад наружу на левой',
          transitionDirection: 2,
          rotationDirection: 2,
          rotationDegree: 360,
          startLeg: 0,
          endLeg: 0,
          isChangeLeg: false,
          startEdge: 1,
          endEdge: 1,
          isChangeEdge: false,
          isSpeedIncrease: false,
          isDifficult: true,
          type: 'turn',
          description: '',
          absoluteName: 'loop',
          distance: 1,
          coordinates: {
            vector: 'east',
            start: {
              x: 26,
              y: 35,
            },
            end: {
              x: 29,
              y: 35,
            },
          },
        },
      ],
    };
  },
  test() {
    return movements;
  },
};
