name: Deploy server front

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare files for transfer
        run: mkdir -p ./deploy && cp -r .next public package.json package-lock.json next.config.js ecosystem.config.js ./deploy

      - name: Clean old backup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /home/genry_bolit/sg-front/old
            rm -rf /home/genry_bolit/sg-front/old/*

      - name: Upload new version (next)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy/*"
          target: "/home/genry_bolit/sg-front/next"

      - name: Copy .env
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            [ -f "/home/genry_bolit/sg-front/.env" ] && \
            cp /home/genry_bolit/sg-front/.env /home/genry_bolit/sg-front/next/.env

      - name: Move folders
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Оригинальная логика перемещения
            if [ -d "/home/genry_bolit/sg-front/current" ]; then
              mv /home/genry_bolit/sg-front/current /home/genry_bolit/sg-front/old/current
            fi
            mv /home/genry_bolit/sg-front/next /home/genry_bolit/sg-front/current

      - name: Install production dependencies
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/genry_bolit/sg-front/current
            npm ci --production

      - name: Restart application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/genry_bolit/sg-front/current
            ./restart.sh
