name: Deploy Next.js frontend

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Remove old folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: "rm -rf /home/genry_bolit/sg-front/old"

      - name: Upload build files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          source: ".next/standalone/*,.next/static/*,public/*"
          target: "/home/${{ secrets.SSH_USERNAME }}/sg-front/next"

      - name: Copy .env
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: "cp /home/genry_bolit/sg-front/.env /home/genry_bolit/sg-front/next/.env"

      - name: Move folders
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mv /home/genry_bolit/sg-front/current /home/genry_bolit/sg-front/old || true
            mv /home/genry_bolit/sg-front/next /home/genry_bolit/sg-front/current

      - name: Restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: "/home/genry_bolit/sg-front/restart.sh"
